// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1bcc36f3-e2d2-444c-a3ca-6a3a6ba5743f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MfD7I03dR",
    "aws_user_pools_web_client_id": "5vgkl7rsc5fvub1pd4jivbk4sk",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://j2rinx62bbgrpmea35ux2g35bu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "transcription": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "language": "en-US"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Kendra",
                    "LanguageCode": "en-US"
                }
            }
        }
    }
};


export default awsmobile;
